fix: milestone card ux updates issue 273
pln-planning-tools/Starmap pull request #282
Opened 2023-01-25 00:20 UTC by djmcquillan

fixes: #273 

- Minor styling updates to the milestone cards

2023-01-25 18:38 UTC, djmcquillan commented
@whizzzkid updated the github icon.  As for the hover state of the cards the hover border change should only occur if there are children for the issue

2023-01-26 00:24 UTC, SgtPooki commented
@djmcquillan when is the github icon supposed to be muted? I would imagine it should be muted at all times unless hover over.. but I'm not sure what you and @juliaxbow talked about

2023-01-26 00:50 UTC, SgtPooki requested changes
just one thing that isn't entirely your code

2023-01-26 00:50 UTC, SgtPooki commented on components/roadmap-grid/grid-row.tsx
> +            <Box w={`${parseInt(milestone.completion_rate.value.toString())}%`} h="100%" borderRadius="20px" bg="#7DE087" />
I see that this is existing code but I'm confused why are we converting a number to a string to an int to a string? 

```
w={`${parseInt(milestone.completion_rate.value.toString())}%`}
```

If there is some need to truncate, we should use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Number/toPrecision where we set `completion_rate`. Could you address that @djmcquillan ?

2023-01-26 01:20 UTC, djmcquillan commented
> @djmcquillan when is the github icon supposed to be muted? I would imagine it should be muted at all times unless hover over.. but I'm not sure what you and @juliaxbow talked about

just based on the figma designs the github icon is always muted unless hovered - update was made to address the non-muted icons in latest commit.

2023-01-28 00:50 UTC, SgtPooki commented
demo looks much better

2023-01-28 00:51 UTC, SgtPooki approved these changes

2023-01-28 01:16 UTC, djmcquillan commented
> demo looks much better

@SgtPooki are you ok with merging these changes in before we address the comments in #273 ?

2023-01-28 02:03 UTC, SgtPooki commented
Yessir. thanks for double checking.. we can adjust later if necessary! Sounds like julia did all the design work required and I was late to the party. sorry for the holdup

2023-01-28 02:03 UTC, SgtPooki commented
ugh. accidentally clicked close instead of comment

2023-01-28 02:15 UTC, merged